### ISSUE TITLE
[Bug] u_int_* is implementation specific and should never be used

### ISSUE THREAD

**Issue by albap** [JuliaLang/openspecfun#34]
`sys/types.h` and its `u_int_*`  should never be used.
`stdint.h` and its `uint_*` is the C99 standard.

**Comment by yuyichao** [comment]
I believe `sys/types.h` is standard. `u_int_*` is not though.

**Comment by albap** [comment]
You're write. My post wasn't clear. It's ``u_int_*`` only that's not standard.

**Comment by albap** [comment]
Here's the fix. Please review and if good apply.
http://sprunge.us/EGTf

**Comment by yuyichao** [comment]
Could you please [submit a pull request](https://help.github.com/articles/using-pull-requests/) instead?

**Comment by albap** [comment]
Are the patches good?
If so I think I can reproduce them in the pull request format.

**Comment by yuyichao** [comment]
FWIW, are `__BEGIN_DECLS` and `__END_DECLS` actually used anywhere? Seems that we can simply remove them.

**Comment by albap** [comment]
Even better then. Less is more. I'll remove the cruft.

**Comment by ViralBShah** [comment]
I wish we can just have julia versions of many of these things eventually.

**Comment by albap** [comment]
@ViralBShah 
I wish julia could be portable and work everywhere with a single version.
Why add complexity? A single standard version that works anywhere is much more rewarding. Less is more.


This is my opinion.
