### ISSUE TITLE
Compilation fails on musl system

### ISSUE THREAD

**Issue by albap** [JuliaLang/openspecfun#41]
Here's the error I get on Alpine Linux (musl libc)
http://pastebin.com/raw/wLifkSst

I think it's due to this commit - https://github.com/JuliaLang/openspecfun/commit/594d953842f23db69227b66e76dbc48779a9af1b by @Keno because it worked before that.

**Comment by Keno** [comment]
Is this fixed if you add `#inlcude <complex.h>` under `#include <math.h>` in `Faddeeva/Faddeeva.h`? Maybe musl's math.h does not include complex.h?

**Comment by albap** [comment]
No, the error remains.

**Comment by Keno** [comment]
Hmm, curious. If you want to try this: https://github.com/JuliaLang/openspecfun/pull/43, fixed all the errors for me. Can you apply that patch and post the exact errors?

**Comment by albap** [comment]
I applied the patch and ran make.
Here's the full log.
http://pastebin.com/raw/x3kJ98XV

**Comment by albap** [comment]
It worked!

**Comment by Keno** [comment]
Sorry, I had made a typo in the first version of my comment. I corrected it right after and it's also fixed in the patch.

**Comment by Keno** [comment]
Great!

**Comment by Keno** [comment]
Fixed by 329998b2f82a0d5d4d81d2344719c06f303b4ba8 then.

**Comment by albap** [comment]
Could you push a new version of openspecfun after this fix? v0.5.2?
Because it's a big deal for musl users.

**Comment by Keno** [comment]
e4df5ae16af1bb4d28729a2fb5a8c2f3a49cf7ad

**Comment by albap** [comment]
Thanks a lot.

**Comment by tkelman** [comment]
I don't think this is musl specific at all, https://github.com/JuliaLang/openspecfun/pull/39 also broke the arm glibc build of julia.
