### ISSUE TITLE
Move to JuliaMath

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/openspecfun#47]
I suggest moving this to the JuliaMath org.

**Comment by ViralBShah** [comment]
Cc @simonbyrne @tkelman

**Comment by tkelman** [comment]
I don't want to do this one (or openlibm) as much as pure-Julia packages because old versions of Julia hardcoded the url in the build system.

**Comment by ViralBShah** [comment]
Won't github auto-forward?

**Comment by tkelman** [comment]
It will, but that would break if anyone were to ever create a new JuliaLang/openspecfun repository. Small risk, but old versions of Julia are not as actively updated as METADATA is.

**Comment by ViralBShah** [comment]
Ok. let's leave it here.
